# Generated by Django 2.1.7 on 2019-03-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_no', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('status_date', models.DateField()),
            ],
        ),
    ]
